# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            jamchamb's jekyll
tagline:          'blog'
description:      'My personal blog.'
url:              https://jamchamb.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           James Chambers
  url:            https://facebook.com/raketemensch

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/alley_2.jpg

social:
#  - icon:         twitter
#    url:          https://twitter.com/iancamporez
#    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/jamchamb
    desc:         GitHub profile

  - icon:         facebook
    url:          https://facebook.com/raketemensch
    desc:         Add me on google+

  - icon:         feed
    url:          https://jamchamb.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         James Chambers
  url:            https://jamchamb.github.io
  type_title:     CC BY-NC 2.5
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-59558217-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
