# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            James Chambers
tagline:          'blog'
description:      'My personal blog.'
url:              https://jamchamb.github.io
baseurl:          
commentsystem:    disqus
disqus:           jamchamb

author:
  name:           James Chambers
  url:            https://plus.google.com/117340791617653200719/

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/alley_2.jpg

social:
#  - icon:         twitter
#    url:          https://twitter.com/iancamporez
#    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/jamchamb
    desc:         My GitHub profile

  - icon:         twitter
    url:          https://twitter.com/jamchambru
    desc:         Twitter

  - icon:         linkedin
    url:          https://linkedin.com/in/jamchamb
    desc:         LinkedIn

  - icon:         feed
    url:          https://jamchamb.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

  - title:	  Projects
    url:	  /projects

copyright:
  author:         James Chambers
  url:            https://plus.google.com/117340791617653200719/?rel=author
  type_title:     CC BY-NC 2.5
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

collections:
  - projects

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-59558217-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
